### ISSUE TITLE
Sensor Recommendations

### ISSUE THREAD

**Issue by tron-zero** [QuickSander/homebridge-soil-temp-sensor#1]
What are the recommended sensors to use with this?

**Comment by QuickSander** [comment]
Hi, home made sensors since you would need to have a sensor which send a specific http POST request conforming to notification-sever format. 

The sensors I use is a capacitive moisture sensor with an ESP8266 breakout board attached to a LiPo battery. 

I made this plugin mainly for my own use thinking it would be very unlikely somebody else will have the same situation. But if you're into a bit of electronics and programming yourself, maybe this is useful.
